export const eventsdata = [
  {
    id: 0,
    status: "Created",
    name: "IPL 2023",
    goLiveDate: "2023-03-29",
    matches: [
      {
        id: 0,
        team1: "Mumbai Indians",
        team2: "Chennai Super Kings",
        date: "2023-03-29",
        time: "19:30",
        venue: "Wankhede Stadium, Mumbai",
        status: "Upcoming",
      },
      {
        id: 1,
        team1: "Kolkata Knight Riders",
        team2: "Delhi Capitals",
        date: "2023-03-30",
        time: "19:30",
        venue: "Eden Gardens, Kolkata",
        status: "Upcoming",
      },
      {
        id: 2,
        team1: "Rajasthan Royals",
        team2: "Royal Challengers Bangalore",
        date: "2023-03-31",
        time: "19:30",
        venue: "Sawai Mansingh Stadium, Jaipur",
        status: "Upcoming",
      },
      {
        id: 3,
        team1: "Sunrisers Hyderabad",
        team2: "Punjab Kings",
        date: "2023-04-01",
        time: "19:30",
        venue: "Rajiv Gandhi International Stadium, Hyderabad",
        status: "Upcoming",
      },
      {
        id: 4,
        team1: "Chennai Super Kings",
        team2: "Kolkata Knight Riders",
        date: "2023-04-02",
        time: "19:30",
        venue: "M. A. Chidambaram Stadium, Chennai",
        status: "Upcoming",
      },
      {
        id: 5,
        team1: "Delhi Capitals",
        team2: "Rajasthan Royals",
        date: "2023-04-03",
        time: "19:30",
        venue: "Arun Jaitley Stadium, Delhi",
        status: "Upcoming",
      },
      {
        id: 6,
        team1: "Royal Challengers Bangalore",
        team2: "Sunrisers Hyderabad",
        date: "2023-04-04",
        time: "19:30",
        venue: "M. Chinnaswamy Stadium, Bangalore",
        status: "Upcoming",
      },
    ],
    teamSizeLimit: 55,
    batsmanLimit: 30,
    bowlerLimit: 15,
    allRounderLimit: 10,
    teamCreationCost: 500,
    userParticipationLimit: 50,
    teamsAllocated: 30,
    winnersLimit: 20,
    prizes: [
      {
        rank: 1,
        amount: 10000,
      },
      {
        rank: 2,
        amount: 7000,
      },
      {
        rank: 3,
        amount: 5000,
      },
      {
        rank: 4,
        amount: 3000,
      },
    ],
    otherPrizes: 50,
  },
  {
    id: 1,
    status: "Released",
    name: "Cricket World Cup 2022",
    goLiveDate: "2022-11-21",
    matches: [
      {
        id: 0,
        team1: "Mumbai Indians",
        team2: "Chennai Super Kings",
        date: "2023-03-29",
        time: "19:30",
        venue: "Wankhede Stadium, Mumbai",
        status: "Upcoming",
      },
      {
        id: 1,
        team1: "Kolkata Knight Riders",
        team2: "Delhi Capitals",
        date: "2023-03-30",
        time: "19:30",
        venue: "Eden Gardens, Kolkata",
        status: "Upcoming",
      },
      {
        id: 2,
        team1: "Rajasthan Royals",
        team2: "Royal Challengers Bangalore",
        date: "2023-03-31",
        time: "19:30",
        venue: "Sawai Mansingh Stadium, Jaipur",
        status: "Upcoming",
      },
      {
        id: 3,
        team1: "Sunrisers Hyderabad",
        team2: "Punjab Kings",
        date: "2023-04-01",
        time: "19:30",
        venue: "Rajiv Gandhi International Stadium, Hyderabad",
        status: "Upcoming",
      },
      {
        id: 6,
        team1: "Royal Challengers Bangalore",
        team2: "Sunrisers Hyderabad",
        date: "2023-04-04",
        time: "19:30",
        venue: "M. Chinnaswamy Stadium, Bangalore",
        status: "Upcoming",
      },
      {
        id: 7,
        team1: "Punjab Kings",
        team2: "Mumbai Indians",
        date: "2023-04-05",
        time: "19:30",
        venue: "Punjab Cricket Association IS Bindra Stadium, Mohali",
        status: "Upcoming",
      },
    ],
    teamSizeLimit: 30,
    batsmanLimit: 10,
    bowlerLimit: 10,
    allRounderLimit: 5,
    teamCreationCost: 200,
    userParticipationLimit: 20,
    teamsAllocated: 19,
    winnersLimit: 10,
    prizes: [
      {
        rank: 1,
        amount: 10000,
      },
      {
        rank: 2,
        amount: 7000,
      },
      {
        rank: 3,
        amount: 5000,
      },
      {
        rank: 4,
        amount: 3000,
      },
    ],
    otherPrizes: 20,
  },
  {
    id: 2,
    status: "Live",
    name: "Cricket League 2022",
    goLiveDate: "2022-12-15",
    matches: [
      {
        id: 2,
        team1: "Rajasthan Royals",
        team2: "Royal Challengers Bangalore",
        date: "2023-03-31",
        time: "19:30",
        venue: "Sawai Mansingh Stadium, Jaipur",
        status: "Upcoming",
      },
      {
        id: 3,
        team1: "Sunrisers Hyderabad",
        team2: "Punjab Kings",
        date: "2023-04-01",
        time: "19:30",
        venue: "Rajiv Gandhi International Stadium, Hyderabad",
        status: "Upcoming",
      },
      {
        id: 4,
        team1: "Chennai Super Kings",
        team2: "Kolkata Knight Riders",
        date: "2023-04-02",
        time: "19:30",
        venue: "M. A. Chidambaram Stadium, Chennai",
        status: "Upcoming",
      },
      {
        id: 5,
        team1: "Delhi Capitals",
        team2: "Rajasthan Royals",
        date: "2023-04-03",
        time: "19:30",
        venue: "Arun Jaitley Stadium, Delhi",
        status: "Upcoming",
      },
      {
        id: 6,
        team1: "Royal Challengers Bangalore",
        team2: "Sunrisers Hyderabad",
        date: "2023-04-04",
        time: "19:30",
        venue: "M. Chinnaswamy Stadium, Bangalore",
        status: "Upcoming",
      },
      {
        id: 7,
        team1: "Punjab Kings",
        team2: "Mumbai Indians",
        date: "2023-04-05",
        time: "19:30",
        venue: "Punjab Cricket Association IS Bindra Stadium, Mohali",
        status: "Upcoming",
      },
    ],
    teamSizeLimit: 40,
    batsmanLimit: 15,
    bowlerLimit: 10,
    allRounderLimit: 5,
    teamCreationCost: 300,
    userParticipationLimit: 30,
    teamsAllocated: 22,
    winnersLimit: 15,
    prizes: [
      {
        rank: 1,
        amount: 10000,
      },
      {
        rank: 2,
        amount: 7000,
      },
      {
        rank: 3,
        amount: 5000,
      },
      {
        rank: 4,
        amount: 3000,
      },
    ],
    otherPrizes: 30,
  },
  {
    id: 3,
    status: "Cancelled",
    name: "Cricket League 2023",
    goLiveDate: "2023-12-15",
    matches: [
      {
        id: 0,
        team1: "Mumbai Indians",
        team2: "Chennai Super Kings",
        date: "2023-03-29",
        time: "19:30",
        venue: "Wankhede Stadium, Mumbai",
        status: "Upcoming",
      },
    ],
    teamSizeLimit: 40,
    batsmanLimit: 15,
    bowlerLimit: 10,
    allRounderLimit: 5,
    teamCreationCost: 300,
    userParticipationLimit: 30,
    teamsAllocated: 14,
    winnersLimit: 15,
    prizes: [
      {
        rank: 1,
        amount: 10000,
      },
      {
        rank: 2,
        amount: 7000,
      },
    ],
    otherPrizes: 30,
  },
  {
    id: 4,
    status: "Completed",
    name: "Cricket League 2024",
    goLiveDate: "2024-12-15",
    matches: [
      {
        id: 0,
        team1: "Mumbai Indians",
        team2: "Chennai Super Kings",
        date: "2023-03-29",
        time: "19:30",
        venue: "Wankhede Stadium, Mumbai",
        status: "Upcoming",
      },
      {
        id: 2,
        team1: "Rajasthan Royals",
        team2: "Royal Challengers Bangalore",
        date: "2023-03-31",
        time: "19:30",
        venue: "Sawai Mansingh Stadium, Jaipur",
        status: "Upcoming",
      },
      {
        id: 3,
        team1: "Sunrisers Hyderabad",
        team2: "Punjab Kings",
        date: "2023-04-01",
        time: "19:30",
        venue: "Rajiv Gandhi International Stadium, Hyderabad",
        status: "Upcoming",
      },
      {
        id: 4,
        team1: "Chennai Super Kings",
        team2: "Kolkata Knight Riders",
        date: "2023-04-02",
        time: "19:30",
        venue: "M. A. Chidambaram Stadium, Chennai",
        status: "Upcoming",
      },
      {
        id: 5,
        team1: "Delhi Capitals",
        team2: "Rajasthan Royals",
        date: "2023-04-03",
        time: "19:30",
        venue: "Arun Jaitley Stadium, Delhi",
        status: "Upcoming",
      },
      {
        id: 6,
        team1: "Royal Challengers Bangalore",
        team2: "Sunrisers Hyderabad",
        date: "2023-04-04",
        time: "19:30",
        venue: "M. Chinnaswamy Stadium, Bangalore",
        status: "Upcoming",
      },
      {
        id: 7,
        team1: "Punjab Kings",
        team2: "Mumbai Indians",
        date: "2023-04-05",
        time: "19:30",
        venue: "Punjab Cricket Association IS Bindra Stadium, Mohali",
        status: "Upcoming",
      },
    ],
    teamSizeLimit: 40,
    batsmanLimit: 15,
    bowlerLimit: 10,
    allRounderLimit: 5,
    teamCreationCost: 300,
    userParticipationLimit: 30,
    teamsAllocated: 28,
    winnersLimit: 15,
    prizes: [
      {
        rank: 1,
        amount: 10000,
      },
      {
        rank: 2,
        amount: 7000,
      },
      {
        rank: 3,
        amount: 5000,
      },
      {
        rank: 4,
        amount: 3000,
      },
      {
        rank: 5,
        amount: 2000,
      },
    ],
    otherPrizes: 30,
  },
];
