export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USERDETAIL_SUCCESS = "GET_USERDETAIL_SUCCESS";
export const GET_VERIFY_SUCCESS = "GET_VERIFY_SUCCESS";

export const GET_USERLIST_SUCCESS = "GET_USERLIST_SUCCESS";