export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const GET_MATCHES_SUCCESS = "GET_MATCHES_SUCCESS";

export const GET_EVENTDETAIL_SUCCESS = "GET_EVENTDETAIL_SUCCESS";
export const GET_EVENTPLAYERSLIST_SUCCESS = "GET_EVENTPLAYERSLIST_SUCCESS";
export const GET_EVENTTEAMLIST_SUCCESS = "GET_EVENTTEAMLIST_SUCCESS";